# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=b'Z\002./',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntask.proto\x12\x08protobuf\"\xf6\x02\n\tTaskInput\x12\x0b\n\x03wbs\x18\x01 \x01(\t\x12\x12\n\nwbs_parent\x18\x02 \x01(\t\x12\x14\n\x0cwbs_children\x18\x03 \x03(\t\x12\x13\n\x0bstatus_date\x18\x04 \x01(\t\x12\x1f\n\x17\x64uration_without_dayoff\x18\x05 \x01(\x05\x12\x1b\n\x13\x64uration_statusdate\x18\x06 \x01(\x05\x12\x0c\n\x04\x63ost\x18\x07 \x01(\x01\x12\x10\n\x08progress\x18\x08 \x01(\x01\x12\x1b\n\x13\x62\x61seline_start_date\x18\t \x01(\t\x12\x19\n\x11\x62\x61seline_end_date\x18\n \x01(\t\x12\x19\n\x11\x62\x61seline_duration\x18\x0b \x01(\x05\x12\x15\n\rbaseline_cost\x18\x0c \x01(\x01\x12\x0c\n\x04\x42\x43WP\x18\r \x01(\x01\x12\x0c\n\x04\x42\x43WS\x18\x0e \x01(\x01\x12\x0b\n\x03SPI\x18\x0f \x01(\x01\x12\x14\n\x0cpercent_plan\x18\x10 \x01(\x01\x12\x16\n\x0epercent_actual\x18\x11 \x01(\x01\"\x90\x01\n\nTaskOutput\x12\x0b\n\x03wbs\x18\x01 \x01(\t\x12\x0c\n\x04\x63ost\x18\x02 \x01(\x01\x12\x10\n\x08progress\x18\x03 \x01(\x01\x12\x0c\n\x04\x42\x43WP\x18\x04 \x01(\x01\x12\x0c\n\x04\x42\x43WS\x18\x05 \x01(\x01\x12\x0b\n\x03SPI\x18\x06 \x01(\x01\x12\x14\n\x0cpercent_plan\x18\x07 \x01(\x01\x12\x16\n\x0epercent_actual\x18\x08 \x01(\x01\"4\n\x0eTaskInputArray\x12\"\n\x05tasks\x18\x01 \x03(\x0b\x32\x13.protobuf.TaskInput\"6\n\x0fTaskOutputArray\x12#\n\x05tasks\x18\x01 \x03(\x0b\x32\x14.protobuf.TaskOutputB\x04Z\x02./b\x06proto3'
)




_TASKINPUT = _descriptor.Descriptor(
  name='TaskInput',
  full_name='protobuf.TaskInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wbs', full_name='protobuf.TaskInput.wbs', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wbs_parent', full_name='protobuf.TaskInput.wbs_parent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wbs_children', full_name='protobuf.TaskInput.wbs_children', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_date', full_name='protobuf.TaskInput.status_date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_without_dayoff', full_name='protobuf.TaskInput.duration_without_dayoff', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_statusdate', full_name='protobuf.TaskInput.duration_statusdate', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cost', full_name='protobuf.TaskInput.cost', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='progress', full_name='protobuf.TaskInput.progress', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='baseline_start_date', full_name='protobuf.TaskInput.baseline_start_date', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='baseline_end_date', full_name='protobuf.TaskInput.baseline_end_date', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='baseline_duration', full_name='protobuf.TaskInput.baseline_duration', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='baseline_cost', full_name='protobuf.TaskInput.baseline_cost', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BCWP', full_name='protobuf.TaskInput.BCWP', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BCWS', full_name='protobuf.TaskInput.BCWS', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SPI', full_name='protobuf.TaskInput.SPI', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='percent_plan', full_name='protobuf.TaskInput.percent_plan', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='percent_actual', full_name='protobuf.TaskInput.percent_actual', index=16,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=399,
)


_TASKOUTPUT = _descriptor.Descriptor(
  name='TaskOutput',
  full_name='protobuf.TaskOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wbs', full_name='protobuf.TaskOutput.wbs', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cost', full_name='protobuf.TaskOutput.cost', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='progress', full_name='protobuf.TaskOutput.progress', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BCWP', full_name='protobuf.TaskOutput.BCWP', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BCWS', full_name='protobuf.TaskOutput.BCWS', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SPI', full_name='protobuf.TaskOutput.SPI', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='percent_plan', full_name='protobuf.TaskOutput.percent_plan', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='percent_actual', full_name='protobuf.TaskOutput.percent_actual', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=546,
)


_TASKINPUTARRAY = _descriptor.Descriptor(
  name='TaskInputArray',
  full_name='protobuf.TaskInputArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tasks', full_name='protobuf.TaskInputArray.tasks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=600,
)


_TASKOUTPUTARRAY = _descriptor.Descriptor(
  name='TaskOutputArray',
  full_name='protobuf.TaskOutputArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tasks', full_name='protobuf.TaskOutputArray.tasks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=602,
  serialized_end=656,
)

_TASKINPUTARRAY.fields_by_name['tasks'].message_type = _TASKINPUT
_TASKOUTPUTARRAY.fields_by_name['tasks'].message_type = _TASKOUTPUT
DESCRIPTOR.message_types_by_name['TaskInput'] = _TASKINPUT
DESCRIPTOR.message_types_by_name['TaskOutput'] = _TASKOUTPUT
DESCRIPTOR.message_types_by_name['TaskInputArray'] = _TASKINPUTARRAY
DESCRIPTOR.message_types_by_name['TaskOutputArray'] = _TASKOUTPUTARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskInput = _reflection.GeneratedProtocolMessageType('TaskInput', (_message.Message,), {
  'DESCRIPTOR' : _TASKINPUT,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.TaskInput)
  })
_sym_db.RegisterMessage(TaskInput)

TaskOutput = _reflection.GeneratedProtocolMessageType('TaskOutput', (_message.Message,), {
  'DESCRIPTOR' : _TASKOUTPUT,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.TaskOutput)
  })
_sym_db.RegisterMessage(TaskOutput)

TaskInputArray = _reflection.GeneratedProtocolMessageType('TaskInputArray', (_message.Message,), {
  'DESCRIPTOR' : _TASKINPUTARRAY,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.TaskInputArray)
  })
_sym_db.RegisterMessage(TaskInputArray)

TaskOutputArray = _reflection.GeneratedProtocolMessageType('TaskOutputArray', (_message.Message,), {
  'DESCRIPTOR' : _TASKOUTPUTARRAY,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.TaskOutputArray)
  })
_sym_db.RegisterMessage(TaskOutputArray)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
